//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjudaTopico
    {
        public AjudaTopico()
        {
            this.Ajuda = new HashSet<Ajuda>();
            this.AjudaTopico1 = new HashSet<AjudaTopico>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public int AjudaTopicoId { get; set; }
    
        public virtual ICollection<Ajuda> Ajuda { get; set; }
        public virtual ICollection<AjudaTopico> AjudaTopico1 { get; set; }
        public virtual AjudaTopico AjudaTopico2 { get; set; }
    }
}
