//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumPorCategoria = new HashSet<AlbumPorCategoria>();
            this.ImagemAlbum = new HashSet<ImagemAlbum>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string UrlAmigavel { get; set; }
        public bool PostarNoFacebook { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<AlbumPorCategoria> AlbumPorCategoria { get; set; }
        public virtual ICollection<ImagemAlbum> ImagemAlbum { get; set; }
    }
}
