//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumPorCategoria
    {
        public int Id { get; set; }
        public int AlbumId { get; set; }
        public int CategoriaAlbumId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual CategoriaAlbum CategoriaAlbum { get; set; }
    }
}
