//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Ingredientes { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public string Imagem { get; set; }
        public bool Ativo { get; set; }
        public int CardapioCategoriaId { get; set; }
    
        public virtual CardapioCategoria CardapioCategoria { get; set; }
    }
}
