//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPortifolio
    {
        public CategoriaPortifolio()
        {
            this.PortifolioPorCategoria = new HashSet<PortifolioPorCategoria>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string UrlAmigavel { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<PortifolioPorCategoria> PortifolioPorCategoria { get; set; }
    }
}
