//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Album = new HashSet<Album>();
            this.CategoriaPublicacao = new HashSet<CategoriaPublicacao>();
            this.Portifolio = new HashSet<Portifolio>();
            this.Produto = new HashSet<Produto>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string UrlAmigavel { get; set; }
        public int StatusId { get; set; }
    
        public virtual ICollection<Album> Album { get; set; }
        public virtual ICollection<CategoriaPublicacao> CategoriaPublicacao { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Portifolio> Portifolio { get; set; }
        public virtual ICollection<Produto> Produto { get; set; }
    }
}
