//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaPublicacao
    {
        public int Id { get; set; }
        public int CategoriaId { get; set; }
        public int PublicacaoId { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Publicacao Publicacao { get; set; }
    }
}
