//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteParceiro
    {
        public ClienteParceiro()
        {
            this.CupomDesconto = new HashSet<CupomDesconto>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public string Tipo { get; set; }
        public int PessoaId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<CupomDesconto> CupomDesconto { get; set; }
    }
}
