//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalhePorImovel
    {
        public int Id { get; set; }
        public int ImovelId { get; set; }
        public int ImovelDetalheId { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual ImovelDetalhe ImovelDetalhe { get; set; }
    }
}
