//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string MimeType { get; set; }
        public string Descricao { get; set; }
        public string Arquivo { get; set; }
        public bool Ativo { get; set; }
    }
}
