//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int Id { get; set; }
        public string Resumo { get; set; }
        public string Endereco { get; set; }
        public string Logo { get; set; }
        public string Email { get; set; }
        public int PessoaId { get; set; }
        public string TemaPainel { get; set; }
        public string Latitute { get; set; }
        public string Longitude { get; set; }
        public string Telefone { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
