//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagemProduto
    {
        public int Id { get; set; }
        public string Imagem { get; set; }
        public string Legenda { get; set; }
        public int Ordem { get; set; }
        public int ProdutoId { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
