//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImovelDetalhe
    {
        public ImovelDetalhe()
        {
            this.DetalhePorImovel = new HashSet<DetalhePorImovel>();
        }
    
        public int Id { get; set; }
        public string Grupo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<DetalhePorImovel> DetalhePorImovel { get; set; }
    }
}
