//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imovel
    {
        public Imovel()
        {
            this.ImagemImovel = new HashSet<ImagemImovel>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string CentralNegocio { get; set; }
        public string Imagem { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> ValorCondominio { get; set; }
        public Nullable<double> AreaTotal { get; set; }
        public Nullable<double> AreaConstruida { get; set; }
        public Nullable<int> Dormitorio { get; set; }
        public Nullable<int> Suite { get; set; }
        public Nullable<int> Banheiro { get; set; }
        public Nullable<int> Garagem { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public string Bairro { get; set; }
        public string Cep { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string UrlAmigavel { get; set; }
        public int TipoContratoId { get; set; }
        public int TipoImovelId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataExclusao { get; set; }
        public string UsuarioExclusao { get; set; }
        public string BairroUrl { get; set; }
        public string CidadeUrl { get; set; }
    
        public virtual ICollection<ImagemImovel> ImagemImovel { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        public virtual TipoImovel TipoImovel { get; set; }
        public virtual Status Status { get; set; }
    }
}
