//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cmsEntities : DbContext
    {
        public cmsEntities()
            : base("name=cmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agenda> Agenda { get; set; }
        public DbSet<Ajuda> Ajuda { get; set; }
        public DbSet<AjudaTopico> AjudaTopico { get; set; }
        public DbSet<Album> Album { get; set; }
        public DbSet<Bairro> Bairro { get; set; }
        public DbSet<Cardapio> Cardapio { get; set; }
        public DbSet<CardapioCategoria> CardapioCategoria { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<CategoriaPublicacao> CategoriaPublicacao { get; set; }
        public DbSet<ClienteParceiro> ClienteParceiro { get; set; }
        public DbSet<Contador> Contador { get; set; }
        public DbSet<Contato> Contato { get; set; }
        public DbSet<CupomDesconto> CupomDesconto { get; set; }
        public DbSet<Depoimento> Depoimento { get; set; }
        public DbSet<Download> Download { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Equipe> Equipe { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<ImagemAlbum> ImagemAlbum { get; set; }
        public DbSet<ImagemImovel> ImagemImovel { get; set; }
        public DbSet<ImagemPortifolio> ImagemPortifolio { get; set; }
        public DbSet<ImagemProduto> ImagemProduto { get; set; }
        public DbSet<ImagemPublicacao> ImagemPublicacao { get; set; }
        public DbSet<Imovel> Imovel { get; set; }
        public DbSet<Link> Link { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Mensagem> Mensagem { get; set; }
        public DbSet<Municipio> Municipio { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Pessoa> Pessoa { get; set; }
        public DbSet<Portifolio> Portifolio { get; set; }
        public DbSet<Produto> Produto { get; set; }
        public DbSet<Promocao> Promocao { get; set; }
        public DbSet<Publicacao> Publicacao { get; set; }
        public DbSet<Rede> Rede { get; set; }
        public DbSet<RedeSocial> RedeSocial { get; set; }
        public DbSet<Regiao> Regiao { get; set; }
        public DbSet<Servico> Servico { get; set; }
        public DbSet<Slide> Slide { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<TipoContato> TipoContato { get; set; }
        public DbSet<TipoContrato> TipoContrato { get; set; }
        public DbSet<TipoImovel> TipoImovel { get; set; }
        public DbSet<TipoServico> TipoServico { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Video> Video { get; set; }
        public DbSet<VwCidade> VwCidade { get; set; }
        public DbSet<VwBairro> VwBairro { get; set; }
    }
}
