//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Imovel = new HashSet<Imovel>();
            this.Imovel1 = new HashSet<Imovel>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string CpfCnpj { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public string Imagem { get; set; }
        public string Bio { get; set; }
        public string Observacao { get; set; }
        public string Interesse { get; set; }
        public string Oferecido { get; set; }
        public string Informacao { get; set; }
        public string DocumentoProfissional { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Whatsapp { get; set; }
        public string Skype { get; set; }
        public bool Ativo { get; set; }
        public string ObservacaoTipoCadastro { get; set; }
        public string Url { get; set; }
        public int PerfilPessoaId { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Imovel> Imovel { get; set; }
        public virtual ICollection<Imovel> Imovel1 { get; set; }
        public virtual PerfilPessoa PerfilPessoa { get; set; }
    }
}
