//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortifolioPorCategoria
    {
        public int Id { get; set; }
        public int PortifolioId { get; set; }
        public int CategoriaPortifolioId { get; set; }
    
        public virtual CategoriaPortifolio CategoriaPortifolio { get; set; }
        public virtual Portifolio Portifolio { get; set; }
    }
}
