//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacao
    {
        public Publicacao()
        {
            this.CategoriaPublicacao = new HashSet<CategoriaPublicacao>();
            this.ImagemPublicacao = new HashSet<ImagemPublicacao>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Resumo { get; set; }
        public string Texto { get; set; }
        public string Imagem { get; set; }
        public System.DateTime DataPublicacao { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public bool ExibirComoPopup { get; set; }
        public bool ExibirImagem { get; set; }
        public string UrlAmigavel { get; set; }
        public bool PostarNoFacebook { get; set; }
        public int StatusId { get; set; }
        public string Autor { get; set; }
    
        public virtual ICollection<CategoriaPublicacao> CategoriaPublicacao { get; set; }
        public virtual ICollection<ImagemPublicacao> ImagemPublicacao { get; set; }
        public virtual Status Status { get; set; }
    }
}
