//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rede
    {
        public Rede()
        {
            this.RedeSocial = new HashSet<RedeSocial>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string UrlBase { get; set; }
        public string Icone { get; set; }
    
        public virtual ICollection<RedeSocial> RedeSocial { get; set; }
    }
}
