//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Resumo { get; set; }
        public string Descricao { get; set; }
        public string Icone { get; set; }
        public string Imagem { get; set; }
        public string UrlAmigavel { get; set; }
        public bool Ativo { get; set; }
        public int TipoId { get; set; }
    
        public virtual TipoServico TipoServico { get; set; }
    }
}
