//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Album = new HashSet<Album>();
            this.Cardapio = new HashSet<Cardapio>();
            this.CardapioCategoria = new HashSet<CardapioCategoria>();
            this.Categoria = new HashSet<Categoria>();
            this.CupomDesconto = new HashSet<CupomDesconto>();
            this.Depoimento = new HashSet<Depoimento>();
            this.Download = new HashSet<Download>();
            this.Imovel = new HashSet<Imovel>();
            this.Link = new HashSet<Link>();
            this.Pessoa = new HashSet<Pessoa>();
            this.Portifolio = new HashSet<Portifolio>();
            this.Produto = new HashSet<Produto>();
            this.Promocao = new HashSet<Promocao>();
            this.Publicacao = new HashSet<Publicacao>();
            this.Servico = new HashSet<Servico>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual ICollection<Album> Album { get; set; }
        public virtual ICollection<Cardapio> Cardapio { get; set; }
        public virtual ICollection<CardapioCategoria> CardapioCategoria { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<CupomDesconto> CupomDesconto { get; set; }
        public virtual ICollection<Depoimento> Depoimento { get; set; }
        public virtual ICollection<Download> Download { get; set; }
        public virtual ICollection<Imovel> Imovel { get; set; }
        public virtual ICollection<Link> Link { get; set; }
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        public virtual ICollection<Portifolio> Portifolio { get; set; }
        public virtual ICollection<Produto> Produto { get; set; }
        public virtual ICollection<Promocao> Promocao { get; set; }
        public virtual ICollection<Publicacao> Publicacao { get; set; }
        public virtual ICollection<Servico> Servico { get; set; }
    }
}
