//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoImovel
    {
        public TipoImovel()
        {
            this.Imovel = new HashSet<Imovel>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string UrlAmigavel { get; set; }
    
        public virtual ICollection<Imovel> Imovel { get; set; }
    }
}
